def _program(name: str, faculty: str, study_area: str, qualification_level: str) -> dict:
    return {
        "name": name,
        "faculty": faculty,
        "study_area": study_area,
        "qualification_level": qualification_level,
        "is_active": True,
    }


ACADEMIC_PROGRAM_GROUPS = {
    "business": [
        _program("Bachelor of Accountancy", "Business and Commerce", "Business", "Bachelor's Degree"),
        _program("Bachelor of Banking and Finance", "Business and Commerce", "Business", "Bachelor's Degree"),
        _program("Bachelor of Business Management", "Business and Commerce", "Business", "Bachelor's Degree"),
        _program("Bachelor of Economics", "Business and Commerce", "Economics", "Bachelor's Degree"),
        _program("Bachelor of Human Resources Management", "Business and Commerce", "Business", "Bachelor's Degree"),
        _program("Bachelor of Marketing Management", "Business and Commerce", "Business", "Bachelor's Degree"),
        _program("Bachelor of Purchasing and Supply Management", "Business and Commerce", "Business", "Bachelor's Degree"),
    ],
    "computing": [
        _program("Bachelor of Computer Science", "Computing and Informatics", "Computing", "Bachelor's Degree"),
        _program("Bachelor of Cyber Security", "Computing and Informatics", "Computing", "Bachelor's Degree"),
        _program("Bachelor of Data Science and Analytics", "Computing and Informatics", "Computing", "Bachelor's Degree"),
        _program("Bachelor of Information Systems", "Computing and Informatics", "Computing", "Bachelor's Degree"),
        _program("Bachelor of Software Engineering", "Computing and Informatics", "Computing", "Bachelor's Degree"),
    ],
    "education": [
        _program("Bachelor of Education in Early Childhood Development", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Educational Leadership", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Primary Education", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Science Education", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Secondary English", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Secondary Mathematics", "Education", "Education", "Bachelor's Degree"),
        _program("Bachelor of Education in Special Needs Education", "Education", "Education", "Bachelor's Degree"),
    ],
    "humanities": [
        _program("Bachelor of Arts in Development Studies", "Humanities and Social Sciences", "Social Sciences", "Bachelor's Degree"),
        _program("Bachelor of Arts in English and Communication", "Humanities and Social Sciences", "Humanities", "Bachelor's Degree"),
        _program("Bachelor of Arts in History and Heritage", "Humanities and Social Sciences", "Humanities", "Bachelor's Degree"),
        _program("Bachelor of Arts in Media and Society Studies", "Humanities and Social Sciences", "Humanities", "Bachelor's Degree"),
        _program("Bachelor of Arts in Peace and Governance", "Humanities and Social Sciences", "Social Sciences", "Bachelor's Degree"),
        _program("Bachelor of Arts in Psychology", "Humanities and Social Sciences", "Social Sciences", "Bachelor's Degree"),
        _program("Bachelor of Social Work", "Humanities and Social Sciences", "Social Sciences", "Bachelor's Degree"),
    ],
    "law": [
        _program("Bachelor of Laws", "Law", "Law", "Bachelor's Degree"),
    ],
    "health": [
        _program("Bachelor of Medicine and Bachelor of Surgery", "Health Sciences", "Health Sciences", "Bachelor's Degree"),
        _program("Bachelor of Nursing Science", "Health Sciences", "Health Sciences", "Bachelor's Degree"),
        _program("Bachelor of Pharmacy", "Health Sciences", "Health Sciences", "Bachelor's Degree"),
        _program("Bachelor of Public Health", "Health Sciences", "Health Sciences", "Bachelor's Degree"),
    ],
    "agriculture": [
        _program("Bachelor of Agricultural Economics", "Agriculture", "Agriculture", "Bachelor's Degree"),
        _program("Bachelor of Agronomy", "Agriculture", "Agriculture", "Bachelor's Degree"),
        _program("Bachelor of Animal Science", "Agriculture", "Agriculture", "Bachelor's Degree"),
        _program("Bachelor of Crop Science", "Agriculture", "Agriculture", "Bachelor's Degree"),
        _program("Bachelor of Food Science and Technology", "Agriculture", "Agriculture", "Bachelor's Degree"),
        _program("Bachelor of Horticulture", "Agriculture", "Agriculture", "Bachelor's Degree"),
    ],
    "engineering": [
        _program("Bachelor of Chemical Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Civil Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Electrical Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Electronic Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Industrial and Manufacturing Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Mechanical Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Mechatronics Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
        _program("Bachelor of Mining Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
    ],
    "applied_sciences": [
        _program("Bachelor of Applied Biology and Biochemistry", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        _program("Bachelor of Biotechnology", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        _program("Bachelor of Environmental Science", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        _program("Bachelor of Geographical Information Science", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        _program("Bachelor of Mathematics and Statistics", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        _program("Bachelor of Physics", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
    ],
    "theology": [
        _program("Bachelor of Divinity", "Theology and Religious Studies", "Theology", "Bachelor's Degree"),
        _program("Bachelor of Pastoral Ministry", "Theology and Religious Studies", "Theology", "Bachelor's Degree"),
        _program("Bachelor of Religious Studies", "Theology and Religious Studies", "Theology", "Bachelor's Degree"),
        _program("Bachelor of Theology", "Theology and Religious Studies", "Theology", "Bachelor's Degree"),
    ],
    "security": [
        _program("Bachelor of Defence and Security Studies", "Security and Strategic Studies", "Security Studies", "Bachelor's Degree"),
        _program("Bachelor of Disaster Risk Management", "Security and Strategic Studies", "Security Studies", "Bachelor's Degree"),
        _program("Bachelor of International Relations and Diplomacy", "Security and Strategic Studies", "Security Studies", "Bachelor's Degree"),
        _program("Bachelor of Peace and Conflict Studies", "Security and Strategic Studies", "Security Studies", "Bachelor's Degree"),
    ],
    "polytechnic": [
        _program("Higher National Diploma in Accountancy", "Commerce", "Business", "Higher National Diploma"),
        _program("Higher National Diploma in Civil Engineering", "Engineering", "Engineering", "Higher National Diploma"),
        _program("Higher National Diploma in Electrical Engineering", "Engineering", "Engineering", "Higher National Diploma"),
        _program("Higher National Diploma in Mechanical Engineering", "Engineering", "Engineering", "Higher National Diploma"),
        _program("National Diploma in Accountancy", "Commerce", "Business", "National Diploma"),
        _program("National Diploma in Automotive Engineering", "Engineering", "Engineering", "National Diploma"),
        _program("National Diploma in Civil Engineering", "Engineering", "Engineering", "National Diploma"),
        _program("National Diploma in Electrical Engineering", "Engineering", "Engineering", "National Diploma"),
        _program("National Diploma in Information Technology", "Applied Technology", "Computing", "National Diploma"),
        _program("National Diploma in Marketing Management", "Commerce", "Business", "National Diploma"),
        _program("National Diploma in Mechanical Engineering", "Engineering", "Engineering", "National Diploma"),
        _program("National Diploma in Purchasing and Supply", "Commerce", "Business", "National Diploma"),
        _program("National Diploma in Secretarial Studies", "Commerce", "Business", "National Diploma"),
        _program("National Diploma in Tourism and Hospitality Management", "Hospitality", "Hospitality", "National Diploma"),
    ],
    "teacher_college": [
        _program("Diploma in Education (Early Childhood Development)", "Teacher Education", "Education", "Diploma"),
        _program("Diploma in Education (Primary)", "Teacher Education", "Education", "Diploma"),
        _program("Diploma in Education (Secondary)", "Teacher Education", "Education", "Diploma"),
        _program("Diploma in Special Needs Education", "Teacher Education", "Education", "Diploma"),
        _program("Diploma in Technical and Vocational Education", "Teacher Education", "Education", "Diploma"),
    ],
    "agricultural_college": [
        _program("Diploma in Agribusiness Management", "Agriculture", "Agriculture", "Diploma"),
        _program("Diploma in Animal Science", "Agriculture", "Agriculture", "Diploma"),
        _program("Diploma in Crop Production", "Agriculture", "Agriculture", "Diploma"),
        _program("Diploma in Horticulture", "Agriculture", "Agriculture", "Diploma"),
        _program("National Diploma in Agriculture", "Agriculture", "Agriculture", "National Diploma"),
    ],
    "industrial_training": [
        _program("National Certificate in Carpentry and Joinery", "Industrial Trades", "Trades", "National Certificate"),
        _program("National Certificate in Electrical Installation", "Industrial Trades", "Trades", "National Certificate"),
        _program("National Certificate in Information and Communication Technology", "Industrial Trades", "Computing", "National Certificate"),
        _program("National Certificate in Motor Mechanics", "Industrial Trades", "Trades", "National Certificate"),
        _program("National Certificate in Plumbing", "Industrial Trades", "Trades", "National Certificate"),
        _program("National Certificate in Welding and Fabrication", "Industrial Trades", "Trades", "National Certificate"),
    ],
    "vocational": [
        _program("National Certificate in Cosmetology", "Vocational Studies", "Vocational Studies", "National Certificate"),
        _program("National Certificate in Garment Construction", "Vocational Studies", "Vocational Studies", "National Certificate"),
        _program("National Certificate in Hairdressing", "Vocational Studies", "Vocational Studies", "National Certificate"),
        _program("National Certificate in Information and Communication Technology", "Vocational Studies", "Computing", "National Certificate"),
        _program("National Certificate in Motor Mechanics", "Vocational Studies", "Trades", "National Certificate"),
        _program("National Certificate in Solar Installation", "Vocational Studies", "Trades", "National Certificate"),
        _program("National Certificate in Welding and Fabrication", "Vocational Studies", "Trades", "National Certificate"),
    ],
}


ZIMBABWE_ACADEMIC_INSTITUTION_SPECS = [
    {
        "name": "Africa University",
        "short_code": "AU",
        "city": "Mutare",
        "region": "Manicaland",
        "country": "Zimbabwe",
        "mission_focus": "Academic formation for service, leadership, and community impact.",
        "contact_email": "admissions@africau.edu",
        "program_groups": ["business", "computing", "humanities", "health", "agriculture"],
        "custom_programs": [
            _program("Bachelor of International Relations", "Humanities and Social Sciences", "Social Sciences", "Bachelor's Degree"),
        ],
    },
    {
        "name": "Arrupe Jesuit University",
        "short_code": "AJU",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Liberal arts, philosophy, and leadership formation.",
        "contact_email": "admissions@arrupe.ac.zw",
        "program_groups": ["business", "humanities", "theology"],
        "custom_programs": [
            _program("Bachelor of Philosophy", "Humanities and Social Sciences", "Humanities", "Bachelor's Degree"),
            _program("Bachelor of Transformational Leadership", "Humanities and Social Sciences", "Leadership", "Bachelor's Degree"),
        ],
    },
    {
        "name": "Bindura University of Science Education",
        "short_code": "BUSE",
        "city": "Bindura",
        "region": "Mashonaland Central",
        "country": "Zimbabwe",
        "mission_focus": "Science, education, and innovation for national development.",
        "contact_email": "admissions@buse.ac.zw",
        "program_groups": ["education", "applied_sciences", "computing", "business"],
    },
    {
        "name": "Catholic University of Zimbabwe",
        "short_code": "CUZ",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Values-based higher education and professional preparation.",
        "contact_email": "admissions@cuz.ac.zw",
        "program_groups": ["business", "humanities", "law", "theology"],
    },
    {
        "name": "Chinhoyi University of Technology",
        "short_code": "CUT",
        "city": "Chinhoyi",
        "region": "Mashonaland West",
        "country": "Zimbabwe",
        "mission_focus": "Technology, enterprise, and applied research.",
        "contact_email": "admissions@cut.ac.zw",
        "program_groups": ["business", "computing", "engineering", "applied_sciences"],
    },
    {
        "name": "Great Zimbabwe University",
        "short_code": "GZU",
        "city": "Masvingo",
        "region": "Masvingo",
        "country": "Zimbabwe",
        "mission_focus": "Heritage, education, and community transformation.",
        "contact_email": "admissions@gzu.ac.zw",
        "program_groups": ["business", "education", "humanities", "law"],
    },
    {
        "name": "Gwanda State University",
        "short_code": "GSU",
        "city": "Gwanda",
        "region": "Matabeleland South",
        "country": "Zimbabwe",
        "mission_focus": "Innovation, mining-region development, and applied science.",
        "contact_email": "admissions@gsu.ac.zw",
        "program_groups": ["business", "agriculture", "applied_sciences", "engineering"],
    },
    {
        "name": "Harare Institute of Technology",
        "short_code": "HIT",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Industrial technology, engineering, and entrepreneurship.",
        "contact_email": "admissions@hit.ac.zw",
        "program_groups": ["business", "computing", "engineering", "applied_sciences"],
    },
    {
        "name": "Lupane State University",
        "short_code": "LSU",
        "city": "Lupane",
        "region": "Matabeleland North",
        "country": "Zimbabwe",
        "mission_focus": "Rural development, agriculture, and applied community research.",
        "contact_email": "admissions@lsu.ac.zw",
        "program_groups": ["agriculture", "business", "education", "humanities"],
    },
    {
        "name": "Manicaland University of Applied Sciences",
        "short_code": "MSUAS",
        "city": "Mutare",
        "region": "Manicaland",
        "country": "Zimbabwe",
        "mission_focus": "Applied engineering, business, and science for production systems.",
        "contact_email": "admissions@msuas.ac.zw",
        "program_groups": ["business", "computing", "engineering", "applied_sciences"],
    },
    {
        "name": "The Pan African University of Minerals Processing",
        "short_code": "PAUMP",
        "city": "Kwekwe",
        "region": "Midlands",
        "country": "Zimbabwe",
        "mission_focus": "Minerals processing, extractives, and industrial value-addition training.",
        "contact_email": "admissions@paump.ac.zw",
        "program_groups": ["business", "engineering", "applied_sciences"],
        "custom_programs": [
            _program("Bachelor of Metallurgical Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
            _program("Bachelor of Minerals Processing Engineering", "Engineering", "Engineering", "Bachelor's Degree"),
            _program("Bachelor of Mining Geology", "Applied Sciences", "Applied Sciences", "Bachelor's Degree"),
        ],
    },
    {
        "name": "Marondera University of Agricultural Sciences and Technology",
        "short_code": "MUAST",
        "city": "Marondera",
        "region": "Mashonaland East",
        "country": "Zimbabwe",
        "mission_focus": "Agriculture, technology, and food systems innovation.",
        "contact_email": "admissions@muast.ac.zw",
        "program_groups": ["agriculture", "business", "engineering", "applied_sciences"],
    },
    {
        "name": "Midlands State University",
        "short_code": "MSU",
        "city": "Gweru",
        "region": "Midlands",
        "country": "Zimbabwe",
        "mission_focus": "Leadership, innovation, and broad-based professional training.",
        "contact_email": "admissions@msu.ac.zw",
        "program_groups": ["business", "computing", "education", "humanities", "law", "applied_sciences"],
    },
    {
        "name": "National University of Science and Technology",
        "short_code": "NUST",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Science, engineering, health, and industrial innovation.",
        "contact_email": "admissions@nust.ac.zw",
        "program_groups": ["business", "computing", "engineering", "applied_sciences", "health"],
    },
    {
        "name": "Reformed Church University",
        "short_code": "RCU",
        "city": "Masvingo",
        "region": "Masvingo",
        "country": "Zimbabwe",
        "mission_focus": "Faith-anchored education and community leadership.",
        "contact_email": "admissions@rcu.ac.zw",
        "program_groups": ["business", "education", "humanities", "theology"],
    },
    {
        "name": "Solusi University",
        "short_code": "SU",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Holistic Christian higher education and service.",
        "contact_email": "admissions@solusi.ac.zw",
        "program_groups": ["business", "education", "health", "theology"],
    },
    {
        "name": "University of Zimbabwe",
        "short_code": "UZ",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "National scholarship across health, science, humanities, and public leadership.",
        "contact_email": "admissions@uz.ac.zw",
        "program_groups": ["business", "computing", "education", "humanities", "law", "health", "agriculture", "engineering", "applied_sciences"],
    },
    {
        "name": "Women's University in Africa",
        "short_code": "WUA",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Women-centred access to professional and leadership education.",
        "contact_email": "admissions@wua.ac.zw",
        "program_groups": ["business", "education", "humanities", "health"],
    },
    {
        "name": "Zimbabwe Ezekiel Guti University",
        "short_code": "ZEGU",
        "city": "Bindura",
        "region": "Mashonaland Central",
        "country": "Zimbabwe",
        "mission_focus": "Faith-informed leadership and professional development.",
        "contact_email": "admissions@zegu.ac.zw",
        "program_groups": ["business", "education", "humanities", "theology"],
    },
    {
        "name": "Zimbabwe National Defence University",
        "short_code": "ZNDU",
        "city": "Mazowe",
        "region": "Mashonaland Central",
        "country": "Zimbabwe",
        "mission_focus": "Security, defence studies, and strategic leadership.",
        "contact_email": "admissions@zndu.ac.zw",
        "program_groups": ["business", "computing", "security"],
    },
    {
        "name": "Zimbabwe Open University",
        "short_code": "ZOU",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Open, distance, and lifelong learning across the national network.",
        "contact_email": "admissions@zou.ac.zw",
        "program_groups": ["business", "computing", "education", "humanities", "law"],
    },
    {
        "name": "Bulawayo Polytechnic",
        "short_code": "BP",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Technical and professional diploma training for industry.",
        "contact_email": "admissions@byo-poly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Gweru Polytechnic",
        "short_code": "GP",
        "city": "Gweru",
        "region": "Midlands",
        "country": "Zimbabwe",
        "mission_focus": "Technical and vocational training for commerce and engineering sectors.",
        "contact_email": "admissions@gweru-poly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Harare Polytechnic",
        "short_code": "HP",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "National polytechnic training in commerce, engineering, and design.",
        "contact_email": "admissions@hararepoly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Joshua Mqabuko Nkomo Polytechnic",
        "short_code": "JMNP",
        "city": "Gwanda",
        "region": "Matabeleland South",
        "country": "Zimbabwe",
        "mission_focus": "Technical skills development for regional industry and enterprise.",
        "contact_email": "admissions@jmnp.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Kwekwe Polytechnic",
        "short_code": "KP",
        "city": "Kwekwe",
        "region": "Midlands",
        "country": "Zimbabwe",
        "mission_focus": "Applied technical training for production, mining, and commerce.",
        "contact_email": "admissions@kwekwepoly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Masvingo Polytechnic",
        "short_code": "MP",
        "city": "Masvingo",
        "region": "Masvingo",
        "country": "Zimbabwe",
        "mission_focus": "Technical diploma pathways in engineering, commerce, and hospitality.",
        "contact_email": "admissions@masvingopoly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Mutare Polytechnic",
        "short_code": "MTP",
        "city": "Mutare",
        "region": "Manicaland",
        "country": "Zimbabwe",
        "mission_focus": "Applied training in business, engineering, and hospitality.",
        "contact_email": "admissions@mutarepoly.ac.zw",
        "program_groups": ["polytechnic"],
    },
    {
        "name": "Belvedere Technical Teachers College",
        "short_code": "BTTC",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Teacher education with technical and vocational specialization.",
        "contact_email": "admissions@belvederecollege.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Hillside Teachers College",
        "short_code": "HTC",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Teacher preparation for primary, secondary, and special needs education.",
        "contact_email": "admissions@hillsidecollege.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Marymount Teachers College",
        "short_code": "MMTC",
        "city": "Mutare",
        "region": "Manicaland",
        "country": "Zimbabwe",
        "mission_focus": "Teacher development for faith-based and community schools.",
        "contact_email": "admissions@marymountcollege.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Masvingo Teachers College",
        "short_code": "MSTC",
        "city": "Masvingo",
        "region": "Masvingo",
        "country": "Zimbabwe",
        "mission_focus": "Teacher education for classroom leadership and learner support.",
        "contact_email": "admissions@masvingoteachers.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Mkoba Teachers College",
        "short_code": "MKTC",
        "city": "Gweru",
        "region": "Midlands",
        "country": "Zimbabwe",
        "mission_focus": "Primary and special-needs teacher development.",
        "contact_email": "admissions@mkobateachers.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Morgan ZINTEC Teachers College",
        "short_code": "MZTC",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Teacher training with strong school-practice integration.",
        "contact_email": "admissions@morganzintec.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Mutare Teachers College",
        "short_code": "MUTC",
        "city": "Mutare",
        "region": "Manicaland",
        "country": "Zimbabwe",
        "mission_focus": "Teacher preparation for primary and secondary school systems.",
        "contact_email": "admissions@mutareteachers.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Nyadire Teachers College",
        "short_code": "NTC",
        "city": "Nyadire",
        "region": "Mashonaland East",
        "country": "Zimbabwe",
        "mission_focus": "Teacher education for rural and mission-school environments.",
        "contact_email": "admissions@nyadireteachers.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Seke Teachers College",
        "short_code": "STC",
        "city": "Chitungwiza",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Teacher education for national school systems and TVET pathways.",
        "contact_email": "admissions@seketeachers.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "United College of Education",
        "short_code": "UCE",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Teacher and education leadership development.",
        "contact_email": "admissions@uce.ac.zw",
        "program_groups": ["teacher_college"],
    },
    {
        "name": "Chibero College of Agriculture",
        "short_code": "CCA",
        "city": "Norton",
        "region": "Mashonaland West",
        "country": "Zimbabwe",
        "mission_focus": "Agriculture, agribusiness, and farm production training.",
        "contact_email": "admissions@chiberoagric.ac.zw",
        "program_groups": ["agricultural_college"],
    },
    {
        "name": "Gwebi College of Agriculture",
        "short_code": "GCA",
        "city": "Gwebi",
        "region": "Mashonaland West",
        "country": "Zimbabwe",
        "mission_focus": "Agricultural science and production systems training.",
        "contact_email": "admissions@gwebiagric.ac.zw",
        "program_groups": ["agricultural_college"],
    },
    {
        "name": "Kushinga Phikelela National Farmers Training College",
        "short_code": "KPNFTC",
        "city": "Marondera",
        "region": "Mashonaland East",
        "country": "Zimbabwe",
        "mission_focus": "Practical agriculture and farm management training.",
        "contact_email": "admissions@kushinga.ac.zw",
        "program_groups": ["agricultural_college"],
    },
    {
        "name": "Mlezu Agricultural College",
        "short_code": "MAC",
        "city": "Esigodini",
        "region": "Matabeleland South",
        "country": "Zimbabwe",
        "mission_focus": "Agricultural extension and production-focused diploma training.",
        "contact_email": "admissions@mlezuagric.ac.zw",
        "program_groups": ["agricultural_college"],
    },
    {
        "name": "Msasa Industrial Training Centre",
        "short_code": "MITC",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Industrial trade training for manufacturing and services.",
        "contact_email": "admissions@msasa-itc.ac.zw",
        "program_groups": ["industrial_training"],
    },
    {
        "name": "Westgate Industrial Training College",
        "short_code": "WITC",
        "city": "Harare",
        "region": "Harare Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Technical trades and industrial skills development.",
        "contact_email": "admissions@westgateitc.ac.zw",
        "program_groups": ["industrial_training"],
    },
    {
        "name": "Beitbridge Vocational Training Centre",
        "short_code": "BVTC",
        "city": "Beitbridge",
        "region": "Matabeleland South",
        "country": "Zimbabwe",
        "mission_focus": "Vocational pathways for youth employment and enterprise.",
        "contact_email": "admissions@beitbridgevtc.ac.zw",
        "program_groups": ["vocational"],
    },
    {
        "name": "Bikita Vocational Training Centre",
        "short_code": "BKVTC",
        "city": "Bikita",
        "region": "Masvingo",
        "country": "Zimbabwe",
        "mission_focus": "Community-rooted vocational training and entrepreneurship skills.",
        "contact_email": "admissions@bikitavtc.ac.zw",
        "program_groups": ["vocational"],
    },
    {
        "name": "Lobengula Vocational Training Centre",
        "short_code": "LVTC",
        "city": "Bulawayo",
        "region": "Bulawayo Metropolitan",
        "country": "Zimbabwe",
        "mission_focus": "Urban vocational and trade-skills training.",
        "contact_email": "admissions@lobengulavtc.ac.zw",
        "program_groups": ["vocational"],
    },
    {
        "name": "Ruwa Vocational Training Centre",
        "short_code": "RVTC",
        "city": "Ruwa",
        "region": "Mashonaland East",
        "country": "Zimbabwe",
        "mission_focus": "Skills training for entrepreneurship and youth employability.",
        "contact_email": "admissions@ruwavtc.ac.zw",
        "program_groups": ["vocational"],
    },
]


def normalize_academic_program_name(value: str | None) -> str:
    return " ".join((value or "").split()).casefold()


def build_academic_program_specs(spec: dict) -> list[dict]:
    by_name = {}
    for group_name in spec.get("program_groups", []):
        for program in ACADEMIC_PROGRAM_GROUPS.get(group_name, []):
            normalized_name = normalize_academic_program_name(program.get("name"))
            if not normalized_name:
                continue
            cleaned_program = dict(program)
            cleaned_program["name"] = " ".join(cleaned_program["name"].split())
            by_name.setdefault(normalized_name, cleaned_program)

    for program in spec.get("custom_programs", []):
        normalized_name = normalize_academic_program_name(program.get("name"))
        if not normalized_name:
            continue
        cleaned_program = dict(program)
        cleaned_program["name"] = " ".join(cleaned_program["name"].split())
        by_name[normalized_name] = cleaned_program

    return sorted(
        by_name.values(),
        key=lambda item: (
            item.get("qualification_level") or "",
            item.get("faculty") or "",
            item["name"],
        ),
    )
